### ISSUE TITLE
收到多次回调

### ISSUE THREAD

**Issue by br3ant** [PrototypeZ/Sq#1]
public static Observable<ActivityResult> startRx(final Fragment fragment, final int requestCode, int maxCount, String target) {
        Intent intent = new Intent(fragment.getContext(), TakePhotoWithCropActivity.class);
        intent.putExtra(Constants.MAX_SELECT_COUNT, maxCount);
        intent.putExtra(Constants.TARGET, target); //目标路径
        Sq.startActivityForResult(fragment, intent, requestCode);
        return Sq.obtainActivityResult(fragment).filter(new Predicate<ActivityResult>() {
            @Override
            public boolean test(ActivityResult activityResult) throws Exception {
                return activityResult.getRequestCode() == requestCode && activityResult.getResultCode() == RESULT_OK;
            }
        });
    }

**Comment by br3ant** [comment]
BehaviorSubject 改成 PublishSubject 吧

**Comment by PrototypeZ** [comment]
@dota2fans 感谢您的建议，我已经更新到 1.2 了，改成 PublishSubject 了，感谢使用 : )

**Comment by PrototypeZ** [comment]
另外，建议您使用类似 
```
RxView.clicks(btn)
    .compose(takePhotoWithCrop(fragment, maxCount, target, requestCode))
    .subscribe();
```
这样的方式进行调用，把 `takePhotoWithCrop` 封装成返回 `ObservableTransformer` 的函数，这样可以在拍照 Activity 起来以后，前一个 Activity 被杀死的情况下也能正常工作，鲁棒性更好~
