### ISSUE TITLE
当前一个Activity被回收...

### ISSUE THREAD

**Issue by spysoos** [PrototypeZ/Sq#2]
你好，demo里发起的Activity被回收后，在返回到发起的Activity时,该Activity是重建后的Activity，它是怎么能继续处理返回的结果的？一直不明白为什么。我自己却不行，我用的是java，难道是Kotlin的黑科技吗？ demo能出个java版本的吗？ 这个问题一直困扰我...好难受

**Comment by PrototypeZ** [comment]
你好，并没有黑科技，实际上我是先用java写，后面为了demo才改成kotlin的，你可以看一下源码，源码就是 java 实现的，其实很简单的，如果有不明白的地方可以加我微信 zjnb1114
